services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:

